export const EDIT_DRIVE = {
  EDIT_DRIVE_REQUEST_ACTION: 'EDIT_DRIVE_REQUEST_ACTION',
  EDIT_DRIVE_SUCCESS_ACTION: 'EDIT_DRIVE_SUCCESS_ACTION',
  EDIT_DRIVE_FAILURE_ACTION: 'EDIT_DRIVE_FAILURE_ACTION',
};
