export const CREATE_TESTCASE = {
  CREATE_TESTCASE_REQUEST_ACTION: 'CREATE_TESTCASE_REQUEST_ACTION',
  CREATE_TESTCASE_SUCCESS_ACTION: 'CREATE_TESTCASE_SUCCESS_ACTION',
  CREATE_TESTCASE_FAILURE_ACTION: 'CREATE_TESTCASE_FAILURE_ACTION',
};
