export const DRIVE_RESULT = {
  DRIVE_RESULT_REQUEST_ACTION: 'DRIVE_RESULT_REQUEST_ACTION',
  DRIVE_RESULT_SUCCESS_ACTION: 'DRIVE_RESULT_SUCCESS_ACTION',
  DRIVE_RESULT_FAILURE_ACTION: 'DRIVE_RESULT_FAILURE_ACTION',
};
