export const PROBLEM_STATEMENT = {
  SET_DETAILS: 'SET_STATEMENT_DETAILS',
  DETAILS_REQUEST: 'STATEMENT_DETAIL_REQUEST',
  SET_ERROR_MESSAGE: 'SET_STATEMENT_ERROR_MESSAGE',
};
export const TIMER = {
  SET_TIMER: 'SET_TIMER',
  TIMER_REQUEST: 'TIMER_REQUEST',
  SET_TIMER_ERROR: 'SET_TIMER_ERROR',
  UPDATE_TIMER: 'UPDATE_TIMER',
};
export const DRIVE = {
  DRIVE_DETAIL_REQUEST: 'DRIVE_DETAIL_REQUEST',
  SET_DETAILS: 'SET_DRIVE_DETAILS',
  SET_ERROR_MESSAGE: 'SET_DRIVE_ERROR_MESSAGE',
  SET_LOADING: 'SET_DRIVE_LOADING',
};

export const USER = {
  SET_DETAILS: 'SET_USER_DETAILS',
};
