// export const ACTION_CONSTANT = "ACTION_CONSTANTS";
export const TIMER = {
    SET_TIMER: 'SET_TIMER',
    TIMER_REQUEST: 'TIMER_REQUEST',
    SET_TIMER_ERROR: 'SET_TIMER_ERROR',
    UPDATE_TIMER: 'UPDATE_TIMER'
}