export const PROBLEM_STATEMENT_REDUCER = {
    SET_STATEMENT: 'SET_STATEMENT',
    STATEMENT_REQUEST: 'STATEMENT_REQUEST'
}

const RULES_REDUCER = {
    SET_RULES: 'SET_RULES',
    RULES_REQUEST: 'RULES_REQUEST'
}
export default RULES_REDUCER;
