export const CANDIDATE_FORM_ACTIONS = {
    CANDIDATE_REQUEST : "CANDIDATE_REQUEST",
    CANDIDATE_DETAILS_SUCCESS : "CANDIDATE_DETAILS_SUCCESS",
    CANDIDATE_DETAILS_FAILURE : "CANDIDATE_DETAILS_FAILURE"
}