export const DOWNLOAD_RESULT = {
  DOWNLOAD_RESULT_REQUEST_ACTION: 'DOWNLOAD_RESULT_REQUEST_ACTION',
  DOWNLOAD_RESULT_SUCCESS_ACTION: 'DOWNLOAD_RESULT_SUCCESS_ACTION',
  DOWNLOAD_RESULT_FAILURE_ACTION: 'DOWNLOAD_RESULT_FAILURE_ACTION',
};
