export const CREATE_DRIVE = {
  CREATE_DRIVE_REQUEST_ACTION: 'CREATE_DRIVE_REQUEST_ACTION',
  CREATE_DRIVE_SUCCESS_ACTION: 'CREATE_DRIVE_SUCCESS_ACTION',
  CREATE_DRIVE_FAILURE_ACTION: 'CREATE_DRIVE_FAILURE_ACTION',
};
