export const EDIT_PROBLEM = {
  EDIT_PROBLEM_REQUEST_ACTION: 'EDIT_PROBLEM_REQUEST_ACTION',
  EDIT_PROBLEM_SUCCESS_ACTION: 'EDIT_PROBLEM_SUCCESS_ACTION',
  EDIT_PROBLEM_FAILURE_ACTION: 'EDIT_PROBLEM_FAILURE_ACTION',
};
