export const CREATE_PROBLEM = {
  CREATE_PROBLEM_REQUEST_ACTION: 'CREATE_PROBLEM_REQUEST_ACTION',
  CREATE_PROBLEM_SUCCESS_ACTION: 'CREATE_PROBLEM_SUCCESS_ACTION',
  CREATE_PROBLEM_FAILURE_ACTION: 'CREATE_PROBLEM_FAILURE_ACTION',
};
